version: '3.3'

services:
  influxdb:
    image: influxdb:2.6
    container_name: influxdb
    ports:
      - '8086:8086'
    env_file:
      - influxdb.env
    volumes:
      - influxdb_data:/var/lib/influxdb2

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    depends_on:
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    env_file:
      - telegraf.env

volumes:
  influxdb_data:
